version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - video-network

networks:
  video-network:
    driver: bridge
